
# creating A user
POST http://localhost:5000/api/users/CreateUser
Content-Type: application/json

{
    "fullName":"JOhn Mungai",
    "email":"jmungai03@gmail.com",
    "phoneNumber":"19391838",
    "password":"12345678",
    "regNo":"sc/com/0031/22"
}